name: Build and Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up Corretto JDK
      run: |
       wget -O- https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz | sudo tar xz -C /opt
       CORRETTO_PATH=$(ls -d /opt/amazon-corretto-*)
       echo "JAVA_HOME=$CORRETTO_PATH" >> $GITHUB_ENV
       echo "$CORRETTO_PATH/bin" >> $GITHUB_PATH

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
