name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20' # This will need to be updated once JDK 20 is available
        distribution: 'corretto' # Change this to 'corretto' if you want to use Amazon Corretto

    - name: Build with Gradle
      run: ./gradlew build
